@baseUrl = http://127.0.0.1:8000/api
@token = 3|YxDPbRvrUvL4cKTAbUne7YXfMTehFdKe6lp6MCHif3f56173

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Member 1",
    "email": "member@mail.com",
    "password": "rahasiadong",
    "password_confirmation": "rahasiadong"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "rizki@example.com",
    "password": "secret123"
}

### Me
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
Accept: application/json

### Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{token}}
Accept: application/json
