@baseUrl = http://127.0.0.1:8000/api
@token = TOKEN_DISINI

### List Projects
GET {{baseUrl}}/projects
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json


### Create Project
POST {{baseUrl}}/projects
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "name": "Project Management API",
  "description": "Backend API for task management"
}


### Get Project Detail
GET {{baseUrl}}/projects/1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json


### Update Project
PUT {{baseUrl}}/projects/1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "name": "Updated Project",
  "description": "Updated description"
}


### Delete Project
DELETE {{baseUrl}}/projects/1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json
