name: Deployment

on:
  workflow_run:
    workflows: ['Laravel CI'] # Sesuaikan dengan 'name' di file CI Anda
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to Laragon via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          fingerprint: ''
          ssh_strict: false
          debug: true
          command_timeout: 30m
          script: |
            cd "D:/laragon/www/task-management-api"

            # Update repositori
            if [ ! -d ".git" ]; then
              git clone https://github.com/rizkikosasih/laravel-task-api.git .
            else
              git fetch origin main
              git reset --hard origin/main
            fi

            # Composer & Migration
            # Pastikan PHP & Composer sudah ada di PATH Windows
            composer install --no-dev --optimize-autoloader --no-interaction

            # Jalankan migrasi (Force karena di production environment)
            php artisan migrate --force

            # JWT & Permissions
            # Gunakan --skip-if-exists agar secret tidak berubah-ubah tiap deploy
            php artisan jwt:secret -n --skip-if-exists

            # Cache & Optimization
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan permission:cache-reset
